from setuptools import setup, find_packages

setup(
    name='facelib',  # Replace with your package's name
    version='0.1.0',  # Replace with your package's version
    author='Ivan Iachnyk',
    author_email='.com',
    description='A brief description of your package',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/your_package_name',  # Replace with your GitHub URL or another URL
    packages=find_packages(),
    install_requires=[
        'absl-py>=2.0.0',
        'astunparse>=1.6.3',
        'attrs>=23.2.0',
        'beautifulsoup4>=4.12.2',
        'cachetools>=5.3.2',
        'certifi>=2023.11.17',
        'cffi>=1.16.0',
        'click>=8.1.7',
        'cloudpickle>=2.2.1',
        'colorama>=0.4.6',
        'deepface>=0.0.80',
        'filelock>=3.13.1',
        'Flask>=3.0.0',
        'gast>=0.5.4',
        'google-auth>=2.26.1',
        'google-auth-oauthlib>=1.2.0',
        'google-pasta>=0.2.0',
        'grpcio>=1.60.0',
        'h5py>=3.10.0',
        'idna>=3.6',
        'imageio>=2.31.4',
        'importlib-metadata>=7.0.0',
        'itsdangerous>=2.1.2',
        'Jinja2>=3.1.2',
        'joblib>=1.2.0',
        'Keras>=2.15.0',
        'Markdown>=3.5.1',
        'MarkupSafe>=2.1.3',
        'matplotlib>=3.8.2',
        'mediapipe>=0.10.9',
        'numpy>=1.26.3',
        'oauthlib>=3.2.2',
        'opencv-contrib-python>=4.9.0.80',
        'opencv-python>=4.9.0.80',
        'Pillow>=10.2.0',
        'protobuf>=3.20.3',
        'pyasn1>=0.5.1',
        'pyasn1-modules>=0.3.0',
        'PyCParser>=2.21',
        'pyparsing>=3.1.1',
        'PySocks>=1.7.1',
        'python-dateutil>=2.8.2',
        'pytz>=2023.3.post1',
        'PyWavelets>=1.4.1',
        'PyYAML>=6.0.1',
        'requests>=2.31.0',
        'requests-oauthlib>=1.3.1',
        'rsa>=4.9',
        'scikit-image>=0.20.0',
        'scikit-learn>=1.3.0',
        'scipy>=1.11.4',
        'six>=1.16.0',
        'sounddevice>=0.4.6',
        'soupsieve>=2.5',
        'tensorboard>=2.15.1',
        'tensorflow>=2.15.0',
        'tensorflow-estimator>=2.15.0',
        'tensorflow-io-gcs-filesystem>=0.31.0',
        'termcolor>=2.4.0',
        'tqdm>=4.66.1',
        'typing-extensions>=4.9.0',
        'urllib3>=2.1.0',
        'Werkzeug>=3.0.1',
        'wheel>=0.41.2',
        'wrapt>=1.14.1',
        'zipp>=3.17.0'
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
)
